image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: 'Build'
        script:
          - echo "Your deployment to staging script goes here..."
          - git submodule update --init --recursive
          - make archive
          - ls -l output/
        services:
          - docker

