image: atlassian/default-image:3

pipelines:
  custom:
    packages:
      - step:
          script:
            - git submodule update --init --recursive
            - make archive
            - mkdir -p dist/
            - cp output/*.deb dist/
            - make archive PACKAGE_TYPE=rpm
            - cp output/*.rpm dist/
          services:
            - docker
          artifacts:
            - dist/**
