name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: prepaire
      run: mkdir -p dist
    - name: build deb
      run: make archive
    - name: save deb
      run: cp output/*.deb dist/
    - name: build rpm
      run: make archive PACKAGE_TYPE=rpm
    - name: save rpm
      run: cp output/*.rpm dist/
    - name: version
      run: |
        version=$(cat .version)
        echo "version=$version" >> $GITHUB_ENV
    - name: release
      uses: actions/create-release@latest
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ env.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload deb
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/hare_${{ env.version }}_amd64.deb
        asset_name: hare_${{ env.version }}_amd64.deb
        asset_content_type: application/x-debian-package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload rpm
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/hare-${{ env.version }}.x86_64.rpm
        asset_name: hare-${{ env.version }}.x86_64.rpm
        asset_content_type: application/x-rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}